services:
  - type: web
    name: TP4-PB
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.comandos:app --host 0.0.0.0 --port $PORT
